# Generated by Django 2.2.5 on 2020-09-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.TextField(max_length=25, unique=True),
        ),
    ]
